services:
  gym80-web:
    build:
      context: .
      args:
        EXPO_PUBLIC_CLOUD_AUTH: "pocketbase-single"
        EXPO_PUBLIC_POCKETBASE_URL: "/pb"
    image: gym80-tracker:zimaboard
    container_name: gym80-tracker
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - ./zima-data/sync:/data
