import { ImageSourcePropType } from "react-native";

const machineImages: Record<string, ImageSourcePropType> = {
  "bezecky-pas.jpg": require("../../assets/machines/bezecky-pas.jpg"),
  "bicepsovy-zdvih-v-sede.jpg": require("../../assets/machines/bicepsovy-zdvih-v-sede.jpg"),
  "bicepsovy-zdvih-opierka-nc.webp": require("../../assets/machines/bicepsovy-zdvih-opierka-nc.webp"),
  "bicepsovy-zdvih-opierka-overview.jpg": require("../../assets/machines/bicepsovy-zdvih-opierka-overview.jpg"),
  "3007_zaklananie do zadu na chrbat_1.webp": require("../../assets/machines/3007_zaklananie do zadu na chrbat_1.webp"),
  "3007_zaklananie do zadu na chrbat_2.jpg": require("../../assets/machines/3007_zaklananie do zadu na chrbat_2.jpg"),
  "3012_tlaky-na-hrudnik-s-opierkou_1.webp": require("../../assets/machines/3012_tlaky-na-hrudnik-s-opierkou_1.webp"),
  "3012_tlaky-na-hrudnik-s-opierkou_2.jpg": require("../../assets/machines/3012_tlaky-na-hrudnik-s-opierkou_2.jpg"),
  "3017_zhyby-a-dipy-s-dopomocou_1.webp": require("../../assets/machines/3017_zhyby-a-dipy-s-dopomocou_1.webp"),
  "3017_zhyby-a-dipy-s-dopomocou_2.jpg": require("../../assets/machines/3017_zhyby-a-dipy-s-dopomocou_2.jpg"),
  "3036_tlaky-na-hrudnik-nadol-v-sede_1.webp": require("../../assets/machines/3036_tlaky-na-hrudnik-nadol-v-sede_1.webp"),
  "3036_tlaky-na-hrudnik-nadol-v-sede_2.jpg": require("../../assets/machines/3036_tlaky-na-hrudnik-nadol-v-sede_2.jpg"),
  "4016_pritah-na-chrbat-v-sede-kladka_1.webp": require("../../assets/machines/4016_pritah-na-chrbat-v-sede-kladka_1.webp"),
  "3001_predkopavanie_1.webp": require("../../assets/machines/3001_predkopavanie_1.webp"),
  "3001_predkopavanie_2.webp": require("../../assets/machines/3001_predkopavanie_2.webp"),
  "3003_zakopavanie_1.webp": require("../../assets/machines/3003_zakopavanie_1.webp"),
  "3003_zakopavanie_2.jpg": require("../../assets/machines/3003_zakopavanie_2.jpg"),
  "3006_lytka-v-stoji_1.webp": require("../../assets/machines/3006_lytka-v-stoji_1.webp"),
  "3006_lytka-v-stoji_2.webp": require("../../assets/machines/3006_lytka-v-stoji_2.webp"),
  "3008_brusny-stroj_1.webp": require("../../assets/machines/3008_brusny-stroj_1.webp"),
  "3008_brusny-stroj_2.jpg": require("../../assets/machines/3008_brusny-stroj_2.jpg"),
  "3014_tricepsovy tlak v sede_1.webp": require("../../assets/machines/3014_tricepsovy tlak v sede_1.webp"),
  "3014_tricepsovy tlak v sede_2.jpg": require("../../assets/machines/3014_tricepsovy tlak v sede_2.jpg"),
  "3016_odtlacanie-na-hrudnik-v-sede_1.webp": require("../../assets/machines/3016_odtlacanie-na-hrudnik-v-sede_1.webp"),
  "3016_odtlacanie-na-hrudnik-v-sede_2.jpg": require("../../assets/machines/3016_odtlacanie-na-hrudnik-v-sede_2.jpg"),
  "3022_rozpazovanie-na-hrudnik-v-sede_1.webp": require("../../assets/machines/3022_rozpazovanie-na-hrudnik-v-sede_1.webp"),
  "3022_rozpazovanie-na-hrudnik-v-sede_2.jpg": require("../../assets/machines/3022_rozpazovanie-na-hrudnik-v-sede_2.jpg"),
  "3027_lytka-v-sede_1.webp": require("../../assets/machines/3027_lytka-v-sede_1.webp"),
  "3027_lytka-v-sede_2.jpg": require("../../assets/machines/3027_lytka-v-sede_2.jpg"),
  "3028_roznozovanie-v-sede_1.webp": require("../../assets/machines/3028_roznozovanie-v-sede_1.webp"),
  "3028_roznozovanie-v-sede_2.jpg": require("../../assets/machines/3028_roznozovanie-v-sede_2.jpg"),
  "3029_znozovanie-v-sede_1.webp": require("../../assets/machines/3029_znozovanie-v-sede_1.webp"),
  "3029_znozovanie-v-sede_2.jpg": require("../../assets/machines/3029_znozovanie-v-sede_2.jpg"),
  "3030_tlak-nohami-v-sede_1.webp": require("../../assets/machines/3030_tlak-nohami-v-sede_1.webp"),
  "3030_tlak-nohami-v-sede_2.jpg": require("../../assets/machines/3030_tlak-nohami-v-sede_2.jpg"),
  "3032_tlaky-na-ramena-v-sede_1.webp": require("../../assets/machines/3032_tlaky-na-ramena-v-sede_1.webp"),
  "3032_tlaky-na-ramena-v-sede_2.jpg": require("../../assets/machines/3032_tlaky-na-ramena-v-sede_2.jpg"),
  "4012_kladkova-veza_1.webp": require("../../assets/machines/4012_kladkova-veza_1.webp"),
  "4116_stahovanie-hornej-kladky_1.webp": require("../../assets/machines/4116_stahovanie-hornej-kladky_1.webp"),
  "4337_lytka-v-predklone-na-opierke_1.webp": require("../../assets/machines/4337_lytka-v-predklone-na-opierke_1.webp"),
  "4337_lytka-v-predklone-na-opierke_2.webp": require("../../assets/machines/4337_lytka-v-predklone-na-opierke_2.webp"),
  "4018_T_bar_chrbat_1.webp": require("../../assets/machines/4018_T_bar_chrbat_1.webp"),
  "4018_T_bar_chrbat_2.jpg": require("../../assets/machines/4018_T_bar_chrbat_2.jpg"),
  "4021_bradla-na-dipy-a-zhyby_1.webp": require("../../assets/machines/4021_bradla-na-dipy-a-zhyby_1.webp"),
  "4021_bradla-na-dipy-a-zhyby_2.jpg": require("../../assets/machines/4021_bradla-na-dipy-a-zhyby_2.jpg"),
  "4026_lytka-v-predklone_1.webp": require("../../assets/machines/4026_lytka-v-predklone_1.webp"),
  "4026_lytka-v-predklone_2.jpg": require("../../assets/machines/4026_lytka-v-predklone_2.jpg"),
  "4031_stanoviste-na-zhyby-dipy-a-brucho_1.webp": require("../../assets/machines/4031_stanoviste-na-zhyby-dipy-a-brucho_1.webp"),
  "4031_stanoviste-na-zhyby-dipy-a-brucho_2.jpg": require("../../assets/machines/4031_stanoviste-na-zhyby-dipy-a-brucho_2.jpg"),
  "4038_zaklony-na-spodny-chrbat_1.webp": require("../../assets/machines/4038_zaklony-na-spodny-chrbat_1.webp"),
  "4038_zaklony-na-spodny-chrbat_2.jpg": require("../../assets/machines/4038_zaklony-na-spodny-chrbat_2.jpg"),
  "4093_scottova-lavicka-na-biceps_1.webp": require("../../assets/machines/4093_scottova-lavicka-na-biceps_1.webp"),
  "4093_scottova-lavicka-na-biceps_2.jpg": require("../../assets/machines/4093_scottova-lavicka-na-biceps_2.jpg"),
  "4096_basic_press_bench_1.webp": require("../../assets/machines/4096_basic_press_bench_1.webp"),
  "4096_basic_press_bench_2.jpg": require("../../assets/machines/4096_basic_press_bench_2.jpg"),
  "4097_basic_press_bench_1.webp": require("../../assets/machines/4097_basic_press_bench_1.webp"),
  "4097_basic_press_bench_2.jpg": require("../../assets/machines/4097_basic_press_bench_2.jpg"),
  "4159_tlak-nohami-sikmo_2.jpg": require("../../assets/machines/4159_tlak-nohami-sikmo_2.jpg"),
  "4307_lavicka-na-brucho_1.webp": require("../../assets/machines/4307_lavicka-na-brucho_1.webp"),
  "4307_lavicka-na-brucho_2.jpg": require("../../assets/machines/4307_lavicka-na-brucho_2.jpg"),
  "4311_stahovanie-kladiek-na-chrbat-v-sede_1.webp": require("../../assets/machines/4311_stahovanie-kladiek-na-chrbat-v-sede_1.webp"),
  "4311_stahovanie-kladiek-na-chrbat-v-sede_2.jpg": require("../../assets/machines/4311_stahovanie-kladiek-na-chrbat-v-sede_2.jpg"),
  "4319_pritah-na-chrbat-v-sede_1.webp": require("../../assets/machines/4319_pritah-na-chrbat-v-sede_1.webp"),
  "4319_pritah-na-chrbat-v-sede_2.jpg": require("../../assets/machines/4319_pritah-na-chrbat-v-sede_2.jpg"),
  "4320_tlaky-na-ramena-nahor-sikmo_1.webp": require("../../assets/machines/4320_tlaky-na-ramena-nahor-sikmo_1.webp"),
  "4320_tlaky-na-ramena-nahor-sikmo_2.jpg": require("../../assets/machines/4320_tlaky-na-ramena-nahor-sikmo_2.jpg"),
  "4322_tlaky-na-ramena-v-sede-s-opierkou_1.webp": require("../../assets/machines/4322_tlaky-na-ramena-v-sede-s-opierkou_1.webp"),
  "4322_tlaky-na-ramena-v-sede-s-opierkou_2.jpg": require("../../assets/machines/4322_tlaky-na-ramena-v-sede-s-opierkou_2.jpg"),
  "4324_tlak-nohami-v-lahu_1.webp": require("../../assets/machines/4324_tlak-nohami-v-lahu_1.webp"),
  "4324_tlak-nohami-v-lahu_2.jpg": require("../../assets/machines/4324_tlak-nohami-v-lahu_2.jpg"),
  "4331_tlaky-na-hrudnik-v-lahu_1.webp": require("../../assets/machines/4331_tlaky-na-hrudnik-v-lahu_1.webp"),
  "4331_tlaky-na-hrudnik-v-lahu_2.jpg": require("../../assets/machines/4331_tlaky-na-hrudnik-v-lahu_2.jpg"),
  "4335_tlaky-na-hrudnik-hore-v-sede_1.webp": require("../../assets/machines/4335_tlaky-na-hrudnik-hore-v-sede_1.webp"),
  "4335_tlaky-na-hrudnik-hore-v-sede_2.jpg": require("../../assets/machines/4335_tlaky-na-hrudnik-hore-v-sede_2.jpg"),
  "4336_zakopavanie-v-sede-1.webp": require("../../assets/machines/4336_zakopavanie-v-sede-1.webp"),
  "4336_zakopavanie-v-sede-2.jpg": require("../../assets/machines/4336_zakopavanie-v-sede-2.jpg"),
  "4341_tlaky-na-hrudnik-sikmo_1.webp": require("../../assets/machines/4341_tlaky-na-hrudnik-sikmo_1.webp"),
  "4341_tlaky-na-hrudnik-sikmo_2.jpg": require("../../assets/machines/4341_tlaky-na-hrudnik-sikmo_2.jpg"),
  "4344_pritah-na-chrbat-na-opierke_1.webp": require("../../assets/machines/4344_pritah-na-chrbat-na-opierke_1.webp"),
  "4344_pritah-na-chrbat-na-opierke_2.jpg": require("../../assets/machines/4344_pritah-na-chrbat-na-opierke_2.jpg"),
  "4346_tlaky-na-hrudnik-sikmo-nadol_1.webp": require("../../assets/machines/4346_tlaky-na-hrudnik-sikmo-nadol_1.webp"),
  "4346_tlaky-na-hrudnik-sikmo-nadol_2.jpg": require("../../assets/machines/4346_tlaky-na-hrudnik-sikmo-nadol_2.jpg"),
  "4350_bicepsovy-zdvih-v-sede_1.webp": require("../../assets/machines/4350_bicepsovy-zdvih-v-sede_1.webp"),
  "4350_bicepsovy-zdvih-v-sede_2.jpg": require("../../assets/machines/4350_bicepsovy-zdvih-v-sede_2.jpg"),
  "4352_vypony-na-brucho-v-sede-s-oporou_1.webp": require("../../assets/machines/4352_vypony-na-brucho-v-sede-s-oporou_1.webp"),
  "4352_vypony-na-brucho-v-sede-s-oporou_2.jpg": require("../../assets/machines/4352_vypony-na-brucho-v-sede-s-oporou_2.jpg"),
  "4353_drepovaci-stroj-s-opierkou_1.webp": require("../../assets/machines/4353_drepovaci-stroj-s-opierkou_1.webp"),
  "4353_drepovaci-stroj-s-opierkou_2.jpg": require("../../assets/machines/4353_drepovaci-stroj-s-opierkou_2.jpg"),
  "4366_bicepsovy-zdvih-v-sede_1.webp": require("../../assets/machines/4366_bicepsovy-zdvih-v-sede_1.webp"),
  "4366_bicepsovy-zdvih-v-sede_2.jpg": require("../../assets/machines/4366_bicepsovy-zdvih-v-sede_2.jpg"),
  "4371_tlaky-na-ramena-hore-v-sede_1.webp": require("../../assets/machines/4371_tlaky-na-ramena-hore-v-sede_1.webp"),
  "4371_tlaky-na-ramena-hore-v-sede_2.jpg": require("../../assets/machines/4371_tlaky-na-ramena-hore-v-sede_2.jpg"),
  "4382_stahovanie-tyce-na-chrbat-v-sede_1.webp": require("../../assets/machines/4382_stahovanie-tyce-na-chrbat-v-sede_1.webp"),
  "4382_stahovanie-tyce-na-chrbat-v-sede_2.jpg": require("../../assets/machines/4382_stahovanie-tyce-na-chrbat-v-sede_2.jpg"),
  "predkopavanie.jpg": require("../../assets/machines/predkopavanie.jpg"),
  "zakopavanie.jpg": require("../../assets/machines/zakopavanie.jpg"),
  "lytka-v-stoji.jpg": require("../../assets/machines/lytka-v-stoji.jpg"),
  "lytka-v-sede.jpg": require("../../assets/machines/lytka-v-sede.jpg"),
  "lytka-v-predklone.jpg": require("../../assets/machines/lytka-v-predklone.jpg"),
  "lytka-v-predklone-na-opierke.jpg": require("../../assets/machines/lytka-v-predklone-na-opierke.jpg"),
  "stahovanie biceps-vystretymi-rukami.jpg": require("../../assets/machines/stahovanie biceps-vystretymi-rukami.jpg"),
  "brusny-stroj.jpg": require("../../assets/machines/brusny-stroj.jpg"),
  "bicepsovy-zdvih.jpg": require("../../assets/machines/bicepsovy-zdvih.jpg"),
  "bradla-na-dipy-a-zhyby.jpg": require("../../assets/machines/bradla-na-dipy-a-zhyby.jpg"),
  "drepovaci-stojan.jpg": require("../../assets/machines/drepovaci-stojan.jpg"),
  "drepovaci-stroj-s-opierkou.jpg": require("../../assets/machines/drepovaci-stroj-s-opierkou.jpg"),
  "hip-thrust-stroj.jpg": require("../../assets/machines/hip-thrust-stroj.jpg"),
  "hyperextenzna-lavicka.jpg": require("../../assets/machines/hyperextenzna-lavicka.jpg"),
  "kladkova-veza.jpg": require("../../assets/machines/kladkova-veza.jpg"),
  "kladky-na-cele-telo.jpg": require("../../assets/machines/kladky-na-cele-telo.jpg"),
  "lavicka-na-brucho.jpg": require("../../assets/machines/lavicka-na-brucho.jpg"),
  "leg-press-s-dvoma-plochami.jpg": require("../../assets/machines/leg-press-s-dvoma-plochami.jpg"),
  "odtlacanie-na-hrudnik-v-sede.jpg": require("../../assets/machines/odtlacanie-na-hrudnik-v-sede.jpg"),
  "pritah-na-chrbat-na-opierke.jpg": require("../../assets/machines/pritah-na-chrbat-na-opierke.jpg"),
  "pritah-na-chrbat-v-predklone.jpg": require("../../assets/machines/pritah-na-chrbat-v-predklone.jpg"),
  "pritah-na-chrbat-v-sede.jpg": require("../../assets/machines/pritah-na-chrbat-v-sede.jpg"),
  "pritah-na-chrbat-v-sede-kladka.jpg": require("../../assets/machines/pritah-na-chrbat-v-sede-kladka.jpg"),
  "roznozovanie-v-sede.jpg": require("../../assets/machines/roznozovanie-v-sede.jpg"),
  "rozpazovanie-na-hrudnik-v-sede.jpg": require("../../assets/machines/rozpazovanie-na-hrudnik-v-sede.jpg"),
  "roztahovanie-noh-v-drepe.jpg": require("../../assets/machines/roztahovanie-noh-v-drepe.jpg"),
  "scottova-lavicka-na-biceps.jpg": require("../../assets/machines/scottova-lavicka-na-biceps.jpg"),
  "smithov-stroj.jpg": require("../../assets/machines/smithov-stroj.jpg"),
  "stahovanie-hornej-kladky.jpg": require("../../assets/machines/stahovanie-hornej-kladky.jpg"),
  "stahovanie-kladiek-na-chrbat-v-sede.jpg": require("../../assets/machines/stahovanie-kladiek-na-chrbat-v-sede.jpg"),
  "stahovanie-tyce-na-chrbat-v-sede.jpg": require("../../assets/machines/stahovanie-tyce-na-chrbat-v-sede.jpg"),
  "stanoviste-na-zhyby-dipy-a-brucho.jpg": require("../../assets/machines/stanoviste-na-zhyby-dipy-a-brucho.jpg"),
  "tlak-nohami-sikmo.jpg": require("../../assets/machines/tlak-nohami-sikmo.jpg"),
  "tlak-nohami-v-lahu.jpg": require("../../assets/machines/tlak-nohami-v-lahu.jpg"),
  "tlak-nohami-v-sede.jpg": require("../../assets/machines/tlak-nohami-v-sede.jpg"),
  "tlak-nohami-45-stupnov.jpg": require("../../assets/machines/tlak-nohami-45-stupnov.jpg"),
  "tlaky-na-ramena-v-sede.jpg": require("../../assets/machines/tlaky-na-ramena-v-sede.jpg"),
  "tlaky-na-ramena-hore-v-sede.jpg": require("../../assets/machines/tlaky-na-ramena-hore-v-sede.jpg"),
  "tlaky-na-hrudnik-nadol-v-sede.jpg": require("../../assets/machines/tlaky-na-hrudnik-nadol-v-sede.jpg"),
  "tlaky-na-hrudnik-s-opierkou.jpg": require("../../assets/machines/tlaky-na-hrudnik-s-opierkou.jpg"),
  "tlaky-na-hrudnik-hore-v-sede.jpg": require("../../assets/machines/tlaky-na-hrudnik-hore-v-sede.jpg"),
  "tlaky-na-hrudnik-sikmo-nadol.jpg": require("../../assets/machines/tlaky-na-hrudnik-sikmo-nadol.jpg"),
  "tlaky-na-hrudnik-sikmo.jpg": require("../../assets/machines/tlaky-na-hrudnik-sikmo.jpg"),
  "tlaky-na-hrudnik-v-lahu.jpg": require("../../assets/machines/tlaky-na-hrudnik-v-lahu.jpg"),
  "tlaky-na-ramena-nahor-sikmo.jpg": require("../../assets/machines/tlaky-na-ramena-nahor-sikmo.jpg"),
  "tlaky-na-ramena-sikmo.jpg": require("../../assets/machines/tlaky-na-ramena-sikmo.jpg"),
  "tlaky-na-ramena-v-sede-s-opierkou.jpg": require("../../assets/machines/tlaky-na-ramena-v-sede-s-opierkou.jpg"),
  "tricepsovy-tlak-v-sede.jpg": require("../../assets/machines/tricepsovy tlak v sede.jpg"),
  "vypony-na-lytka-v-sede-s-oporou.jpg": require("../../assets/machines/vypony-na-lytka-v-sede-s-oporou.jpg"),
  "zaklony-na-spodny-chrbat.jpg": require("../../assets/machines/zaklony-na-spodny-chrbat.jpg"),
  "zakopavanie-v-lahu.jpg": require("../../assets/machines/zakopavanie-v-lahu.jpg"),
  "zhyby-a-dipy-s-dopomocou.jpg": require("../../assets/machines/zhyby-a-dipy-s-dopomocou.jpg")
};

export function getMachineImage(imageAsset?: string) {
  if (!imageAsset) {
    return null;
  }

  return machineImages[imageAsset] ?? null;
}
